# dwmwal generated colors
foreground #cec4de
background #18141f
cursor #cec4de
selection_foreground #18141f
selection_background #cec4de
color0 #18141f
color1 #4f3c71
color2 #79405a
color3 #558145
color4 #7f8949
color5 #664d91
color6 #995172
color7 #cec4de
color8 #5a5463
color9 #9d81d0
color10 #d38aab
color11 #a5d793
color12 #d0da9b
color13 #b9a4dd
color14 #e1adc4
color15 #cec4de
