# xsettingsd config - apply settings to running GTK apps on dwm
# Styled to match gtk-3.0/settings.ini + gtkrc-2.0 (Miami26 + Kora)
# Chạy: xsettingsd -c ~/.config/xsettingsd/xsettingsd.conf

Net/ThemeName "Miami26"
Net/IconThemeName "kora-pgrey"

Gtk/FontName "Noto Sans 10"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 24
Gtk/MonospaceFontName "JetBrains Mono 10"

Gtk/ColorScheme "prefer-dark"

Gtk/EnableAnimations 1
Gtk/DecorationLayout "menu:minimize,maximize,close"